version: '3.7'

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - ./data:/loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
